apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-http-prod
spec:
  acme:
    email: {{ .Values.email | quote }}
    server: {{ .Values.server | quote }}
    privateKeySecretRef:
      name: {{ .Values.privateKeySecretName | quote }}
    solvers:
      - http01:
          ingress:
            class: {{ .Values.ingressClassName | default "traefik" | quote }}
