apiVersion: v1
kind: Secret
metadata:
  name: cloudstack-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
    cloud-config: |
      [Global]
      api-url = "{{ .Values.apiUrl }}"
      api-key = {{ .Values.apiKey }}
      secret-key = {{ .Values.secretKey }}
      ssl-no-verify = true
